### ISSUE TITLE
Bootstrap 5 support

### ISSUE THREAD

**Issue by irsyadulibad** [sahrullahh/windzo#2]
Hello, your template is amazing and cool...but, unfortunately, for backend dev we need for bootstrap 5

**Comment by sahrullahh** [comment]
will be available soon for version bootstrap,  can be wait because this dashboard not finished yet, so I'll focus on this one first

**Comment by Cicco2132** [comment]
hello, your template give me this problem
 ERROR  Error: The project seems to require yarn but it's not installed.
Error: The project seems to require yarn but it's not installed.
    at checkYarn (D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\@vue\cli-shared-utils\lib\env.js:46:43)
    at exports.hasProjectYarn (D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\@vue\cli-shared-utils\lib\env.js:42:10) 
    at D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\@vue\cli-service\lib\commands\serve.js:314:34
    at Hook.eval [as callAsync] (eval at create (D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:44:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\tapable\lib\Hook.js:18:14)
    at Watching._done (D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\webpack\lib\Watching.js:287:28)
    at D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\webpack\lib\Watching.js:209:21
    at Compiler.emitRecords (D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\webpack\lib\Compiler.js:906:5)
    at D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\webpack\lib\Watching.js:187:22
    at D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\webpack\lib\Compiler.js:872:14

i have followed your repository instructions, but don't work
