### ISSUE TITLE
yarn 

### ISSUE THREAD

**Issue by Cicco2132** [sahrullahh/windzo#7]
hello, your template give me this problem
ERROR Error: The project seems to require yarn but it's not installed.
Error: The project seems to require yarn but it's not installed.
at checkYarn (D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules@vue\cli-shared-utils\lib\env.js:46:43)
at exports.hasProjectYarn (D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules@vue\cli-shared-utils\lib\env.js:42:10)
at D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules@vue\cli-service\lib\commands\serve.js:314:34
at Hook.eval [as callAsync] (eval at create (D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\tapable\lib\HookCodeFactory.js:33:10), :44:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\webpack\lib\Watching.js:287:28)
at D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\webpack\lib\Watching.js:209:21
at Compiler.emitRecords (D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\webpack\lib\Compiler.js:906:5)
at D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\webpack\lib\Watching.js:187:22
at D:\Cartella C\Esp32\Vueprojects\windzo-master\node_modules\webpack\lib\Compiler.js:872:14

i have followed your repository instructions, but don't work

**Comment by sahrullahh** [comment]
Hello @Cicco2132, thank you for using my template, do you have the yarn package? , if not, try to install it first

here are the step :
`npm install --global yarn`

and install all dependency 
`yarn install `

hope it helps you
